from .settings import (
    FEISHU_APP_ID,
    FEISHU_APP_SECRET,
    FEISHU_WEBHOOK_URL,
    FEISHU_SIGNING_KEY,
    DINGTALK_WEBHOOK_URL,
    DINGTALK_SIGNING_KEY,

    WECOME_WEBHOOK_URL,

    BING_URL,
    BING_API,
)
