name: Daily Bing Wallpaper to Feishu

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:  # 允许手动触发

jobs:
  send_bing_wallpaper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 确保检出代码

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run script
      run: |
        source venv/bin/activate
        python main.py
      env:
        FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
        FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        FEISHU_SIGNING_KEY: ${{ secrets.FEISHU_SIGNING_KEY }}  # 签名密钥
